#!/bin/bash

#SBATCH -n 8                              # Number of cores
#SBATCH --time=40:00:00                    # hours:minutes:seconds
#SBATCH --mem-per-cpu=32000
#SBATCH --tmp=4000                         # per node!!
#SBATCH --gpus=rtx_2080_ti:1                         # Ohter options are: --gpus=gtx_1080_ti:1  --gpus=rtx_2080_ti:1
#SBATCH --job-name=train_male_cvae
#SBATCH --output=./jobs/train_cvae.out
#SBATCH --error=./jobs/train_cvae.err


# env2lmod
#module load gcc/8.2.0 python_gpu/3.10.4 open3d/0.9.0 boost/1.74.0
#conda activate grasp_conda ## change conda name accordingly
#python opt_grasppose.py --exp_name pretrained_male --gender male --pose_ckpt_path pretrained/pretrained_model/male_grasppose_model.pt --object camera --n_object_samples 10

conda activate $HOME/grasp
module load gcc/8.2.0 python_gpu/3.10.4 open3d/0.9.0 boost/1.74.0
python train_grasppose.py --data_path ./dataset/GraspPose --gender male --exp_name male_cvae
